$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  samples:
    type: string
  outdir:
    type: string

  envmodules:
    type: object
    properties:
      cellranger:
        type: string
    required:
      - cellranger

  cellranger:
    type: object
    properties:
      reference:
        type: string
      jobmode:
        type: string
      threads:
        type: integer
      memory_per_cpu:
        type: integer
    required:
      - reference

# entries that have to be in the config file for successful validation
required:
  - envmodules
  - samples
  - outdir
  - cellranger
