# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
outdir: "/data/gpfs-1/users/cofu10_c/scratch/test_multipipe"

# Configure the correspondent environmental modules for version control
envmodules:
    cellranger: "/fast/groups/ag_ludwig/Modules/modulefiles/cellranger-atac/2.1.0"
cellranger:
    # Path of folder containing 10x-compatible reference (--reference)
    reference: "/data/gpfs-1/groups/ag_ludwig/work/genome_ref/refdata-cellranger-arc-GRCh38-2020-mtMask"
    # Job manager to use.
    #jobmode: default #slurm, local, sge
    # misc
    #threads: 4
    #memory_per_cpu: 64

resources:
    default:
        threads: 1
        mem_mb: 8000
        walltime: 480
    cellranger:
        threads: 1
        mem_mb: 64000
